vim.keymap.set("n", "<leader>gg", [[<cmd>G<cr>]], {})
vim.keymap.set("x", "<leader>p", [["_dP]], {})
vim.keymap.set("n", "]q", function()
  vim.cmd("cnext")
end, {})
vim.keymap.set("n", "[q", function()
  vim.cmd("cprev")
end, {})
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")

vim.keymap.set("n", "gD", vim.lsp.buf.declaration, {})
vim.keymap.set("n", "gd", vim.lsp.buf.definition, {})
vim.keymap.set("n", "gr", vim.lsp.buf.references, {})
-- vim.keymap.set("n", "<leader>vf", function()
--   vim.lsp.buf.format({
--     filter = function(client)
--       local excludes = {
--         "lua_ls",
--         "pylsp",
--       }
--       return not vim.tbl_contains({client.name, excludes})
--     end,
--   })
-- end, {})
vim.keymap.set("n", "<leader>vh", vim.lsp.buf.hover, {})
vim.keymap.set("n", "<leader>vrn", vim.lsp.buf.rename, {})
vim.keymap.set("n", "<leader>vsd", vim.diagnostic.open_float, {})
vim.keymap.set("n", "<leader>vsh", vim.lsp.buf.signature_help, {})
vim.keymap.set("n", "<leader>va", vim.lsp.buf.code_action, {})
vim.keymap.set("v", "<leader>va", vim.lsp.buf.code_action, {})
vim.keymap.set("n", "<leader>vih", function()
  vim.lsp.inlay_hint.enable(0, not vim.lsp.inlay_hint.is_enabled())
end, {})
vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, {})
vim.keymap.set("n", "]d", vim.diagnostic.goto_next, {})

vim.keymap.set("n", "<leader>tt", function()
  require("tillb.terminal").goto_terminal(1)
end, {})
vim.keymap.set("n", "<leader>tn", function()
  require("tillb.terminal").goto_new_terminal()
end, {})
vim.keymap.set("n", "<leader>tg", function()
  require("tillb.terminal").goto_terminal()
end, {})
vim.keymap.set("n", "<leader>te", function()
  require("tillb.terminal").edit_makeprg()
end, {})
vim.keymap.set("n", "<leader>tm", function()
  require("tillb.terminal").terminal_make()
end, {})
