#!/bin/bash

DOTFILES_REPO_DIR=${DOTFILES_REPO_DIR:-$HOME/Projects/dotfiles}
DOTFILES_DIR=$HOME/.dotfiles

action=$1

usage() {
    case "$1" in
    commands)
        echo "Usage: dotty [install|links|uninstall|clean] OPTIONS"
        ;;
    esac
}

if [ "$action" != "install" ] &&
    [ "$action" != "links" ] &&
    [ "$action" != "uninstall" ] &&
    [ "$action" != "clean" ]; then
    usage commands
    exit 1
fi

function link_dotfiles() {
    echo "Linking dotfiles repo"
    ln -sfn $(pwd) $DOTFILES_DIR
    echo
}

function link_subdirs() {
    echo "Linking subdirs in .$1"
    [[ -d ".$1" ]] || mkdir ".$1"
    for item in $1/*; do
        target=$DOTFILES_DIR/$item
        linkname=$HOME/.$item

        ln -svfn $target $linkname
    done
    echo
}

function link_home() {
    echo "Linking files in home"
    for item in $(ls -A home); do
        if [ "$item" == *.template ] || [ "$item" == *.rendered ]; then
            continue
        fi

        target=$DOTFILES_DIR/home/$item
        linkname=$HOME/$(basename $item)

        ln -svfn $target $linkname
    done
    echo
}

function list_links() {
    for file in $(fd --hidden -t l . ~ 2>/dev/null); do
        if readlink $file | grep $DOTFILES_DIR >/dev/null; then
            echo $file
        fi
    done
}

function install() {
    pushd $DOTFILES_REPO_DIR
    link_dotfiles
    link_subdirs config
    link_subdirs local
    link_subdirs ssh
    ln -svfn ../../dotty $HOME/.local/bin/dotty
    link_home
    popd
}

function uninstall() {
    for link in $(list_links); do
        echo "Removing link $link"
        \rm $link
    done
}

function clean() {
    pushd $DOTFILES_REPO_DIR
    for file in $(fd --hidden -t f '.*\.rendered$' .); do
        echo "Removing $file"
        \rm $file
    done
    popd
}

case "$action" in
install)
    install
    ;;
uninstall)
    uninstall
    ;;
clean)
    clean
    ;;
links)
    list_links
    ;;
esac
