#!/bin/bash

DOTFILES_DIR=$HOME/.dotfiles

function link_dotfiles() {
    echo "Linking dotfiles repo"
    ln -sfn $(pwd) $DOTFILES_DIR
    echo
}

function link_subdirs() {
    echo "Linking subdirs in .$1"
    for item in $1/*; do
        target=$DOTFILES_DIR/$item
        linkname=$HOME/.$item

        ln -svfn $target $linkname
    done
    echo
}

function link_home() {
    echo "Linking files in home"
    for item in $(ls -A home); do
        target=$DOTFILES_DIR/home/$item
        linkname=$HOME/$(basename $item)

        ln -svfn $target $linkname
    done
    echo
}

link_dotfiles
link_subdirs config
link_subdirs local
link_home
