ACCENT_BG=ff5c57
ARC_TRANSPARENCY=True
ARC_WIDGET_BORDER_COLOR=525359
BASE16_GENERATE_DARK=True
BASE16_INVERT_TERMINAL=False
BASE16_MILD_TERMINAL=False
BG=1e1f29
BTN_BG=1e1f29
BTN_FG=eff0eb
BTN_OUTLINE_OFFSET=-3
BTN_OUTLINE_WIDTH=1
CARET1_FG=f1f1f0
CARET2_FG=f1f1f0
CARET_SIZE=0.04
CINNAMON_OPACITY=1.0
FG=f1f1f0
GRADIENT=0.0
GTK3_GENERATE_DARK=True
HDR_BG=1e1f29
HDR_BTN_BG=34353e
HDR_BTN_FG=eff0eb
HDR_FG=eff0eb
ICONS_ARCHDROID=ff5c57
ICONS_DARK=78787e
ICONS_LIGHT=9aedfe
ICONS_LIGHT_FOLDER=9aedfe
ICONS_MEDIUM=57c7ff
ICONS_NUMIX_STYLE=0
ICONS_STYLE=gnome_colors
ICONS_SYMBOLIC_ACTION=eff0eb
ICONS_SYMBOLIC_PANEL=f1f1f0
MATERIA_PANEL_OPACITY=0.6
MATERIA_SELECTION_OPACITY=0.32
MATERIA_STYLE_COMPACT=True
MENU_BG=1e1f29
MENU_FG=eff0eb
NAME=base16/snazzy.yml
OUTLINE_WIDTH=1
ROUNDNESS=2
SEL_BG=ff5c57
SEL_FG=34353e
SPACING=3
SPOTIFY_PROTO_BG=1e1f29
SPOTIFY_PROTO_FG=eff0eb
SPOTIFY_PROTO_SEL=ff5c57
SURUPLUS_GRADIENT1=eff0eb
SURUPLUS_GRADIENT2=ff5c57
SURUPLUS_GRADIENT_ENABLED=False
TERMINAL_ACCENT_COLOR=ff5c57
TERMINAL_BACKGROUND=1e1f29
TERMINAL_BASE_TEMPLATE=monovedek
TERMINAL_COLOR0=1e1f29
TERMINAL_COLOR1=ff5c57
TERMINAL_COLOR10=5af78e
TERMINAL_COLOR11=f3f99d
TERMINAL_COLOR12=57c7ff
TERMINAL_COLOR13=ff6ac1
TERMINAL_COLOR14=9aedfe
TERMINAL_COLOR15=f1f1f0
TERMINAL_COLOR2=5af78e
TERMINAL_COLOR3=ff9f43
TERMINAL_COLOR4=57c7ff
TERMINAL_COLOR5=ff6ac1
TERMINAL_COLOR6=9aedfe
TERMINAL_COLOR7=eff0eb
TERMINAL_COLOR8=34353e
TERMINAL_COLOR9=ff5c57
TERMINAL_FOREGROUND=f1f1f0
TERMINAL_THEME_ACCURACY=128
TERMINAL_THEME_AUTO_BGFG=True
TERMINAL_THEME_EXTEND_PALETTE=False
TERMINAL_THEME_MODE=manual
THEME_STYLE=materia
TXT_BG=4a4b53
TXT_FG=f1f1f0
UNITY_DEFAULT_LAUNCHER_STYLE=False
WM_BORDER_FOCUS=ff5c57
WM_BORDER_UNFOCUS=1e1f29
