#!/bin/sh

bspc config border_width 2
bspc config window_gap 5

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config single_monocle true
bspc config paddingless_monocle false
bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config focus_follows_pointer true
bspc config honor_size_hints false 

##Color settings
bspc config focused_border_color "#f8f8f2"
bspc config normal_border_color "#43454f"
bspc config presel_feedback_color "#f8f8f2"

# This creates and names desktops for multiple monitors.
workspaces_multimonitor &

bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh

bspc rule -a "Tor Browser" state=floating
# bspc rule -a firefox desktop='VI' 
bspc rule -a firefox:*:Picture-in-Picture state=floating
bspc rule -a Zathura state=floating
bspc rule -a Sxiv state=floating
bspc rule -a discord desktop='IX' follow=off  
bspc rule -a Spotify desktop='X' follow=off state=pseudo_tiled
bspc rule -a mpv focus=off state=floating rectangle=450x250+1450+720
bspc rule -a Bitwarden state=floating center=on rectangle=800x600+0+0


### Autostart apps

sxhkd &

# multimonitor support. Save monitor configurations with "autorandr.sh --save <profile>"
# autorandr --change
# bspc wm --reorder-monitors DVI-D-0 HDMI-0
workspaces_multimonitor

xsetroot -cursor_name left_ptr &
sh ~/.fehbg &
# light-locker &

# wacom buttons
xsetwacom set 11 Button 1 11
xsetwacom set 11 Button 2 12
xsetwacom set 11 Button 3 13

picom -b &
dock.sh

xcape -e 'Caps_Lock=Escape'

# System tray applets
nm-applet &
# mate-power-manager &
# pamac-tray &
# clipit &
pasystray &
redshift-gtk &
# syncthing-gtk &
blueman-applet &
