# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/565aeaa1-0e66-49e8-87f3-23edd8cbdc75";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" "noautodefrag" ];
    };

  boot.initrd.luks.devices."nixenc".device = "/dev/disk/by-uuid/01596fe5-7d4b-483c-96a9-22927ab50227";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/565aeaa1-0e66-49e8-87f3-23edd8cbdc75";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" "noautodefrag" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1FF2-A6FE";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/43f79a15-42ea-4142-9053-d150d4611dd6"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
