local opts = { noremap = true, silent = true }
vim.keymap.set(0, "n", "[j", function()
  require("tbung.jupyter").goto_previous_cell_start()
end, opts)
vim.keymap.set(0, "n", "[J", function()
  require("tbung.jupyter").goto_previous_cell_end()
end, opts)
vim.keymap.set(0, "n", "]j", function()
  require("tbung.jupyter").goto_next_cell_start()
end, opts)
vim.keymap.set(0, "n", "]J", function()
  require("tbung.jupyter").goto_next_cell_end()
end, opts)
vim.keymap.set(0, "x", "ij", function()
  require("tbung.jupyter").select_cell(0)
end, opts)
vim.keymap.set(0, "o", "ij", function()
  require("tbung.jupyter").select_cell(0)
end, opts)
